language:
  - cpp
env:
  global:
   # The next declration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "YwdYHh5U9EtSUTm+QHvdbKBfE3l3fJkg915xhzRju+3w9a1PHutBtEM5cHf6B3tz7MfS+n2daUUY4IzA76hv0tJBBStnU0M6bf9zct9SUx+a82cV/KlOLN0kYaBRysRojFa5hjUL5tzmWl3hgAMA4zgZKv/QvW7Ts/A1/RI651I="

compiler:
  - gcc

install:
  - sudo sh -c 'echo deb http://unv-debs.moreofthesa.me.uk precise main >>/etc/apt/sources.list'
  - sudo apt-key adv --keyserver x-hkp://pool.sks-keyservers.net --recv-key 06AF4C14
  - sudo sh -c 'echo deb http://ppa.launchpad.net/purplekarrot/ppa/ubuntu precise main >>/etc/apt/sources.list'
  - sudo apt-key adv --keyserver x-hkp://pool.sks-keyservers.net --recv-key D4762858
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install libwebp-dev libglew-dev libgmp-dev libjpeg8-dev libcurl4-gnutls-dev libfreetype6-dev libgeoip-dev libncursesw5-dev libogg-dev libopenal-dev libpng-dev libsdl2-dev libspeexdsp-dev libtheora-dev libvorbis-dev libopusfile-dev libxvidcore-dev nettle-dev zlib1g-dev cmake

before_script:
  - wget http://clang.llvm.org/libstdc++4.6-clang11.patch;
  - wget "http://gcc.gnu.org/viewcvs/gcc/branches/gcc-4_7-branch/libstdc%2B%2B-v3/include/std/condition_variable?view=patch&r1=193528&r2=193527&pathrev=193528" -O libstdc++4.6-thread-fix.patch
  - sudo patch /usr/include/c++/4.6/type_traits < libstdc++4.6-clang11.patch;
  - sudo patch /usr/include/c++/4.6/condition_variable < libstdc++4.6-thread-fix.patch;

script:
  - sed -i 's/POSITION_INDEPENDENT_CODE 1/COMPILE_FLAGS "-fPIC"/' CMakeLists.txt
  - mkdir -p build
  - cd build
  - CXXFLAGS="-D__extern_always_inline=inline" cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build .

notifications:
  irc:
    - "irc.freenode.org#unvanquished-dev"
    - "irc.quakenet.org#unvanquished"
  on_success: change
  on_failure: always

branches:
  except:
    - debian

addons:
  coverity_scan:
    project:
      name: "Unvanquished/Unvanquished"
      description: "Daemon Engine!"
    notification_email: vcelestialragev@gmail.com
    build_command_prepend: "mkdir build;cd build;CXXFLAGS=\"-D__extern_always_inline=inline\" cmake -DCMAKE_BUILD_TYPE=Debug -DUSE_SDL2=OFF .."
    build_command: "cmake --build ."
    branch_pattern: coverity_scan
